Description: " "

Resources:
  HITTCompanyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: HITTCompanyVPC

  HITTCompanyInternetGateway: # Gateway internet for Public Subnet
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: HITTCompanyInternetGateway

  HITTCompanyAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref HITTCompanyVPC
      InternetGatewayId: !Ref HITTCompanyInternetGateway

  # Public Subnet
  HITTCompanyPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HITTCompanyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet

  # Private Subnet
  HITTCompanyPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HITTCompanyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet

  # Creating JumpBox Security Group
  HITTCompanyJumpBoxEC2PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref HITTCompanyVPC
      GroupDescription: "Public Security Group allowing only SSH"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0        
  
  # Creating the Public Subnet Security Group
  HITTCompanyPublicEC2PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref HITTCompanyVPC
      GroupDescription: "Public Security Group Regulating traffic from SSH, HTTP, and HTTPS"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref HITTCompanyJumpBoxEC2PublicSecurityGroup
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0      

  # Creating the Private Subnet Security Group        
  HITTCompanyPrivateEC2PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref HITTCompanyVPC
      GroupDescription: "Allowing only SSH from JumpBox"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref HITTCompanyJumpBoxEC2PublicSecurityGroup

  # Creating the Public Subnet Route Table
  HITTCompanyPublicEC2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref HITTCompanyVPC
      Tags:
        - Key: Name
          Value: HITTCompany-publicroutetable

  HITTCompanyDefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: HITTCompanyAttachGateway
    Properties:
      RouteTableId: !Ref HITTCompanyPublicEC2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref  HITTCompanyInternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref HITTCompanyPublicEC2RouteTable
      SubnetId: !Ref HITTCompanyPublicSubnet

  # Creating the Private Subnet Route Table
  HITTCompanyPrivateEC2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref HITTCompanyVPC

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref HITTCompanyPrivateEC2RouteTable
      SubnetId: !Ref HITTCompanyPrivateSubnet
    
  # Jumpbox Instance block has been created
  HITTCompanyJumpBoxEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: L00187650HITT_KEY 
      ImageId: ami-00385a401487aefa4
      SubnetId: !Ref   HITTCompanyPublicSubnet
      SecurityGroupIds: 
        - !Ref HITTCompanyJumpBoxEC2PublicSecurityGroup
      Tags:
        - Key: Name
          Value: HITTCompany-JB Public

  HITTCompanyPublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: L00187650HITT_KEY
      ImageId: ami-00385a401487aefa4
      SubnetId: !Ref HITTCompanyPublicSubnet
      SecurityGroupIds: 
        - !Ref HITTCompanyPublicEC2PublicSecurityGroup
      Tags:
        - Key: Name
          Value: HITTCompany-PublicInstance

  HITTCompanyPrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro 
      KeyName: L00187650HITT_KEY 
      ImageId: ami-00385a401487aefa4
      SubnetId: !Ref HITTCompanyPrivateSubnet
      SecurityGroupIds: 
        - !Ref HITTCompanyPrivateEC2PrivateSecurityGroup
      Tags:
        - Key: Name
          Value: HITTCompany-PrivateInstance